yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'


urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import CommentViewSet, CustomUserViewSet, GroupViewSet, PostViewSet

router = DefaultRouter()
router.register(r"users", CustomUserViewSet, basename="users")
router.register(
    r"posts/(?P<post_id>\d+)/comments", CommentViewSet, basename="comments"
)
router.register(r"posts", PostViewSet, basename="posts")
router.register(r"groups", GroupViewSet, basename="groups")


urlpatterns = [
    path("", include(router.urls)),
    path("api-auth/", include("rest_framework.urls")),
    path("", include("djoser.urls")),
    path("auth/", include("djoser.urls.authtoken")),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.PostListView.as_view(), name="index"),
    path(
        "group/<slug:slug>/",
        views.GroupPostListView.as_view(),
        name="post_of_group",
    ),
    path(
        "posts/<int:post_id>/",
        views.PostDetailView.as_view(),
        name="post_detail",
    ),
    path("create/", views.PostCreateView.as_view(), name="post_create"),
    path(
        "posts/<int:post_id>/edit/",
        views.PostUpdateView.as_view(),
        name="post_edit",
    ),
    path(
        "posts/<int:post_id>/delete/",
        views.PostDeleteView.as_view(),
        name="post_delete",
    ),
    path("search/", views.SearchPost.as_view(), name="search"),
    path("follow/", views.PostFollowListView.as_view(), name="follow_index"),
    path(
        "profile/follow/",
        views.AddDeleteFollowing.as_view(),
        name="profile_follow",
    ),
    path(
        "comments/<int:pk>/delete/",
        views.CommentDeleteView.as_view(),
        name="comment_delete",
    ),
    path(
        "comments/<int:pk>/edit/",
        views.CommentEditView.as_view(),
        name="comment_edit",
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path

from . import views

app_name = "users"


urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup"),
    path(
        "logout/",
        LogoutView.as_view(template_name="users/logged_out.html"),
        name="logout",
    ),
    path(
        "login/",
        LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "password_reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html"
        ),
        name="password_reset_form",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_change/",
        PasswordChangeView.as_view(
            template_name="users/password_change_form.html"
        ),
        name="password_change_form",
    ),
    path(
        "password_change/done/",
        PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("me/", views.ProfileView.as_view(), name="me"),
    path(
        "users/<str:username>/",
        views.ProfileDetailView.as_view(),
        name="profile",
    ),
    path("profile_edit", views.UserEditView.as_view(), name="profile_edit"),
    path("users/", views.UserListView.as_view(), name="user_list"),
    path(
        "subscriptions/",
        views.SubscriptionListView.as_view(),
        name="subscription_list",
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

handler404 = "core.views.page_not_found"
handler403 = "core.views.csrf_failure"
handler500 = "core.views.server_error"

urlpatterns = [
    path("", include("posts.urls", namespace="posts")),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include("about.urls", namespace="about")),
    path("api/v1/", include("api.urls")),
    path(
        "redoc/",
        TemplateView.as_view(template_name="redoc.html"),
        name="redoc",
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVector, SearchVectorField
from django.db import models
from django.db.models import Count
from django.urls import reverse

from .fields import WEBPField

User = get_user_model()


class PostQuerySet(models.QuerySet):
    def get_views_count(self):
        """Количество просмотров поста."""
        queryset = self.annotate(
            views_count=Count("view_posts", distinct=True)
        )
        return queryset

    def get_count_posts_of_author(self):
        """Количество постов у определенного автора."""
        queryset = self.annotate(
            count_posts_of_author=Count("author__posts", distinct=True)
        )
        return queryset


class PostManager(models.Manager):
    def get_queryset(self) -> models.QuerySet:
        return PostQuerySet(self.model, using=self._db)

    def get_views_count(self):
        """Количество просмотров поста."""
        return self.get_queryset().get_views_count()

    def get_count_posts_of_author(self):
        """Количество постов у определенного автора."""
        return self.get_queryset().get_count_posts_of_author()


class Group(models.Model):
    """Модель групп."""

    title = models.CharField(max_length=200, verbose_name="название")
    description = models.TextField(verbose_name="описание")
    slug = models.SlugField(
        max_length=100, unique=True, verbose_name="имя страницы группы"
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Группа"
        verbose_name_plural = "Группы"


class Post(models.Model):
    """Модель постов."""

    title = models.CharField(
        "Заголовок", max_length=150, blank=True, null=True
    )
    text = models.TextField(verbose_name="текст поста")
    pub_date = models.DateTimeField(
        auto_now_add=True, verbose_name="дата публикации"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="имя автора",
    )
    group = models.ForeignKey(
        "Group",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="posts",
        verbose_name="название группы",
    )
    image = WEBPField("Картинка", upload_to="posts/", blank=True)
    search_vector = SearchVectorField(null=True)
    objects = PostManager()

    class Meta:
        indexes = [
            GinIndex(fields=["search_vector"]),
        ]
        ordering = ["-pub_date"]
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

    def __str__(self):
        return self.text[:15]

    def get_absolute_url(self):
        return reverse("posts:post_detail", kwargs={"post_id": self.pk})

    def update_search_vector(self) -> None:
        qs = Post.objects.filter(pk=self.pk)
        qs.update(
            search_vector=SearchVector("title", "text", config="russian")
        )


class Comment(models.Model):
    """Модель комментариев."""

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="пост",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comment",
        verbose_name="имя автора",
    )
    text = models.TextField(verbose_name="текст комментария")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ["-created"]
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"


class ViewPost(models.Model):
    """Модель для отслеживания уникальных просмотров пользователем."""

    post = models.ForeignKey(
        to=Post, on_delete=models.CASCADE, related_name="view_posts"
    )
    user = models.ForeignKey(
        to=User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="view_posts",
    )
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    date_of_viewing = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.ip_address} просмотрел {self.post} - {self.date_of_viewing}"

    class Meta:
        verbose_name = "Просмотр"
        verbose_name_plural = "Просмотры"
        constraints = [
            models.UniqueConstraint(
                fields=("post", "user"), name="unique_view_post"
            )
        ]

yatube/templates/includes/comments.html
<!-- Комментарии к посту -->
<div class="col-lg">
  <div class="card my-4">
    <!-- Форма для комментария -->
    <div>
      {% if user.is_authenticated %}
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
          <form method="post" action="">
            {% csrf_token %}
            <div class="form-group mb-2">{{ form.text }}</div>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
        </div>
      {% endif %}
    </div> <!-- Форма для комментария -->

    <!-- Списсок оставленных комментариев к посту -->
    <div>
      {% for comment in comments %}
        <div class="card border-dark text-bg-dark w-75 m-3">
          <h5 class="card-header">{{ comment.author.username }}</h5>
          <div class="card-body">
            <h5 class="card-title">{{ comment.author.username }}</h5>
            <p class="card-text">{{ comment.text }}</p>

            {% if request.user != comment.author %}
              <a href="#" class="btn btn-primary">Ответить</a>
            {% else %}
              <a href="{% url 'posts:comment_delete' comment.pk %}" class="btn btn-danger">Удалить</a>
              <a href="{% url 'posts:comment_edit' comment.pk %}" class="btn btn-primary">Редактировать</a>
            {% endif %}
            <small>{{ comment.created }}</small>
          </div>
        </div>
      {% endfor %}
    </div> <!-- Списсок оставленных комментариев к посту -->
  </div>
</div> <!-- Комментарии к посту -->

yatube/templates/includes/footer.html
{% load static %}
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-expand-lg" style="background-color: #55555571;">
    <div class="container-fluid">

        <a class="navbar-brand" href="{% url 'posts:index' %}">
            <img class="logo" src="{% static 'img/logo.png' %}" width="60" height="60" class="d-inline-block align-top" alt="Логотип">
            Yatube
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'posts:index' %}">Главная</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'posts:post_create' %}">Новая запись</a></li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:follow_index' %}">Лента</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'about:tech' %}">Технологии</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'about:author' %}">Об авторе</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'users:subscription_list' %}">Подписки</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'users:user_list' %}">Пользователи</a></li>

                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown me-3">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'users:me' %}">Личный кабинет</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:password_reset_form' %}">Изменить пароль</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item me-2"><a class="nav-link" href="{% url 'users:login' %}">Войти</a></li>
                <li class="nav-item me-2"><a class="nav-link" href="{% url 'users:signup' %}">Регистрация</a></li>
                {% endif %}


            </ul>
            <form class="d-flex" role="search" method="get" action="{% url 'posts:search' %}">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
                <button class="btn btn-outline-primary" type="submit">Search</button>
            </form>
        </div>

    </div>
</nav>

yatube/templates/includes/post_list.html
{% load thumbnail %}
{% load static %}
<!-- Контент поста -->
<div class="post col-12 col-lg-3">
  <!-- Картинка -->
  <div>
    {% if post.image %}
      {% thumbnail post.image '500x300' crop='center' upscale=True as im %}
      <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="post_header" />
      {% endthumbnail %}
    {% else %}
      <img src="{% static 'img/default_img.png' %}" width="300" height="200" class="post_header" />
    {% endif %}
  </div> <!-- Картинка -->

  <!-- Описание поста -->
  <div class="post_body">
    <!-- Заголовок группы с сылкой -->
    {% if post.group %}
      <span class="color_for_group"><a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a></span>
    {% endif %}
    <!-- Заголовок группы с сылкой -->

    <!-- Заголовок поста -->
    <h4>
      {% autoescape off %}
        {% if post.headline %}
          {{ post.headline }}
        {% else %}
          {{ post.title }}
        {% endif %}
      {% endautoescape %}
    </h4> <!-- Заголовок поста -->

    <!-- Текст поста -->
    <p class="post_text">
      {% autoescape off %}
        {% if post.bodyline %}
          {{ post.bodyline|truncatewords:90 }}
        {% else %}
          {{ post.text|truncatewords:15 }}
        {% endif %}
      {% endautoescape %}
    </p> <!-- Текст поста -->

    <a href="{% url 'posts:post_detail' post.id %}">подробнее</a>

    <!-- Автор поста -->
    <p style="display: flex;">
      {% if post.author.avatar %}
        {% thumbnail post.author.avatar '50x50' crop='center' upscale=True as im %}
        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" />
        {% endthumbnail %}
      {% else %}
        <img src="/media/users/default.png" width="50" height="50" />
      {% endif %}
      {{ post.author.get_full_name }}
    </p> <!-- Автор поста -->

    <!-- Дата публикации поста -->
    <p>{{ post.pub_date|date:'d E Y' }}</p>
  </div> <!-- Описание поста -->
</div> <!-- Контент поста -->