yatube/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import CommentViewSet, CustomUserViewSet, GroupViewSet, PostViewSet

router = DefaultRouter()
router.register(r"users", CustomUserViewSet, basename="users")
router.register(
    r"posts/(?P<post_id>\d+)/comments", CommentViewSet, basename="comments"
)
router.register(r"posts", PostViewSet, basename="posts")
router.register(r"groups", GroupViewSet, basename="groups")


urlpatterns = [
    path("", include(router.urls)),
    path("api-auth/", include("rest_framework.urls")),
    path("", include("djoser.urls")),
    path("auth/", include("djoser.urls.authtoken")),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.PostListView.as_view(), name="index"),
    path(
        "group/<slug:slug>/",
        views.GroupPostListView.as_view(),
        name="post_of_group",
    ),
    path(
        "posts/<int:post_id>/",
        views.PostDetailView.as_view(),
        name="post_detail",
    ),
    path("create/", views.PostCreateView.as_view(), name="post_create"),
    path(
        "posts/<int:post_id>/edit/",
        views.PostUpdateView.as_view(),
        name="post_edit",
    ),
    path(
        "posts/<int:post_id>/delete/",
        views.PostDeleteView.as_view(),
        name="post_delete",
    ),
    path("search/", views.SearchPost.as_view(), name="search"),
    path("follow/", views.PostFollowListView.as_view(), name="follow_index"),
    path(
        "profile/follow/",
        views.AddDeleteFollowing.as_view(),
        name="profile_follow",
    ),
    path(
        "comments/<int:pk>/delete/",
        views.CommentDeleteView.as_view(),
        name="comment_delete",
    ),
    path(
        "comments/<int:pk>/edit/",
        views.CommentEditView.as_view(),
        name="comment_edit",
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path

from . import views

app_name = "users"


urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup"),
    path(
        "logout/",
        LogoutView.as_view(template_name="users/logged_out.html"),
        name="logout",
    ),
    path(
        "login/",
        LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "password_reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html"
        ),
        name="password_reset_form",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_change/",
        PasswordChangeView.as_view(
            template_name="users/password_change_form.html"
        ),
        name="password_change_form",
    ),
    path(
        "password_change/done/",
        PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("me/", views.ProfileView.as_view(), name="me"),
    path(
        "users/<str:username>/",
        views.ProfileDetailView.as_view(),
        name="profile",
    ),
    path("profile_edit", views.UserEditView.as_view(), name="profile_edit"),
    path("users/", views.UserListView.as_view(), name="user_list"),
    path(
        "subscriptions/",
        views.SubscriptionListView.as_view(),
        name="subscription_list",
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

handler404 = "core.views.page_not_found"
handler403 = "core.views.csrf_failure"
handler500 = "core.views.server_error"

urlpatterns = [
    path("", include("posts.urls", namespace="posts")),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include("about.urls", namespace="about")),
    path("api/v1/", include("api.urls")),
    path(
        "redoc/",
        TemplateView.as_view(template_name="redoc.html"),
        name="redoc",
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVector, SearchVectorField
from django.db import models
from django.db.models import Count
from django.urls import reverse

from .fields import WEBPField

User = get_user_model()


class PostQuerySet(models.QuerySet):
    def get_views_count(self):
        """Количество просмотров поста."""
        queryset = self.annotate(
            views_count=Count("view_posts", distinct=True)
        )
        return queryset

    def get_count_posts_of_author(self):
        """Количество постов у определенного автора."""
        queryset = self.annotate(
            count_posts_of_author=Count("author__posts", distinct=True)
        )
        return queryset


class PostManager(models.Manager):
    def get_queryset(self) -> models.QuerySet:
        return PostQuerySet(self.model, using=self._db)

    def get_views_count(self):
        """Количество просмотров поста."""
        return self.get_queryset().get_views_count()

    def get_count_posts_of_author(self):
        """Количество постов у определенного автора."""
        return self.get_queryset().get_count_posts_of_author()


class Group(models.Model):
    """Модель групп."""

    title = models.CharField(max_length=200, verbose_name="название")
    description = models.TextField(verbose_name="описание")
    slug = models.SlugField(
        max_length=100, unique=True, verbose_name="имя страницы группы"
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Группа"
        verbose_name_plural = "Группы"


class Post(models.Model):
    """Модель постов."""

    title = models.CharField(
        "Заголовок", max_length=150, blank=True, null=True
    )
    text = models.TextField(verbose_name="текст поста")
    pub_date = models.DateTimeField(
        auto_now_add=True, verbose_name="дата публикации"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="имя автора",
    )
    group = models.ForeignKey(
        "Group",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="posts",
        verbose_name="название группы",
    )
    image = WEBPField("Картинка", upload_to="posts/", blank=True)
    search_vector = SearchVectorField(null=True)
    objects = PostManager()

    class Meta:
        indexes = [
            GinIndex(fields=["search_vector"]),
        ]
        ordering = ["-pub_date"]
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

    def __str__(self):
        return self.text[:15]

    def get_absolute_url(self):
        return reverse("posts:post_detail", kwargs={"post_id": self.pk})

    def update_search_vector(self) -> None:
        qs = Post.objects.filter(pk=self.pk)
        qs.update(
            search_vector=SearchVector("title", "text", config="russian")
        )


class Comment(models.Model):
    """Модель комментариев."""

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="пост",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comment",
        verbose_name="имя автора",
    )
    text = models.TextField(verbose_name="текст комментария")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ["-created"]
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"


class ViewPost(models.Model):
    """Модель для отслеживания уникальных просмотров пользователем."""

    post = models.ForeignKey(
        to=Post, on_delete=models.CASCADE, related_name="view_posts"
    )
    user = models.ForeignKey(
        to=User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="view_posts",
    )
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    date_of_viewing = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.ip_address} просмотрел {self.post} - {self.date_of_viewing}"

    class Meta:
        verbose_name = "Просмотр"
        verbose_name_plural = "Просмотры"
        constraints = [
            models.UniqueConstraint(
                fields=("post", "user"), name="unique_view_post"
            )
        ]

yatube/posts/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import (
    Exists,
    OuterRef,
    Prefetch,
)
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    FormView,
    UpdateView,
)
from django.views.generic.detail import SingleObjectMixin
from users.models import Follow

from .forms import CommentForm, FollowForm, PostForm
from .mixins import (
    CacheMixin,
    IsAuthorAndLoginRequiredMixin,
    PostMixinListView,
    SearchMixin,
)
from .models import Comment, Post
from .signals import post_view_signal

User = get_user_model()


class PostListView(CacheMixin, PostMixinListView):
    """Класс представления списка постов."""

    def get_queryset(self):
        queryset = super().get_queryset()
        cache_name = "index_cache"
        return self.get_cache(queryset, cache_name, self.cache_timeout)


class SearchPost(SearchMixin, PostMixinListView):
    """Класс представления для поиска постов."""

    pass


class PostDetailView(View):
    """Класс представления определенного поста."""

    def get(self, request, *args, **kwargs):
        view = PostDetail.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = CommentCreateView.as_view()
        return view(request, *args, **kwargs)


class PostDetail(DetailView):
    """Класс представления определенного поста."""

    model = Post
    queryset = Post.objects.select_related("author", "group")
    template_name = "posts/post_detail.html"
    pk_url_kwarg = "post_id"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "form": CommentForm(self.request.POST or None),
                "form_follow": FollowForm(
                    initial={"author": self.object.author}
                ),
            }
        )
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.get_views_count()
        queryset = queryset.get_count_posts_of_author()
        if self.request.user.is_authenticated:
            queryset = queryset.annotate(
                is_subscribed=Exists(
                    self.request.user.follower.filter(
                        author=OuterRef("author_id")
                    )
                )
            )
        comments = (
            Comment.objects.filter(post_id=self.kwargs.get("post_id"))
            .select_related("author")
            .order_by("-created")
        )
        queryset = queryset.prefetch_related(
            Prefetch("comments", queryset=comments)
        )
        return queryset

    def get_object(self, queryset=None):
        obj = super().get_object()
        post_view_signal.send(sender=Post, instance=obj, request=self.request)
        return obj


class PostCreateView(LoginRequiredMixin, CreateView):
    """Класс представление для создания поста."""

    model = Post
    form_class = PostForm

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        form = self.get_form()
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        return super().form_valid(form)


class PostUpdateView(IsAuthorAndLoginRequiredMixin, UpdateView):
    """Класс представление для редактирования поста."""

    form_class = PostForm
    model = Post
    pk_url_kwarg = "post_id"

    def get_redirect_url(self):
        return self.get_object().get_absolute_url()


class PostDeleteView(IsAuthorAndLoginRequiredMixin, DeleteView):
    """Класс для удаления автором своего поста."""

    model = Post
    pk_url_kwarg = "post_id"
    success_url = reverse_lazy("posts:index")

    def get_redirect_url(self):
        return self.get_object().get_absolute_url()


class GroupPostListView(CacheMixin, PostMixinListView):
    """Класс представления списка постов по определенной группе."""

    def get_queryset(self):
        slug = self.kwargs.get("slug")
        queryset = super().get_queryset().filter(group__slug=slug)
        cache_name = f"posts_of_group_cache_{slug}"
        return self.get_cache(queryset, cache_name, self.cache_timeout)


class PostFollowListView(LoginRequiredMixin, CacheMixin, PostMixinListView):
    """Класс представления постов избранных авторов."""

    def get_queryset(self):
        user = self.request.user
        queryset = super().get_queryset().filter(author__following__user=user)
        cache_name = f"post_follow_cache_{user.id}"
        return self.get_cache(queryset, cache_name, self.cache_timeout)


class AddDeleteFollowing(LoginRequiredMixin, View):
    """
    Класс представление для добавления автора в избранные
    или удаления автора из избранных.
    """

    def post(self, request):
        author_id = request.POST.get("author")
        author = get_object_or_404(User, pk=author_id)
        if author == request.user:
            messages.error(request, "Вы не можете подписать на самого себя.")
            return redirect(request.META.get("HTTP_REFERER", "/"))
        msg = f"Вы подписались на пользователя {author.username}"
        instance, created = Follow.objects.get_or_create(
            author=author, user=request.user
        )
        if not created:
            instance.delete()
            msg = "Подписка отменена."
        messages.success(request, msg)
        return redirect(request.META.get("HTTP_REFERER", "/"))


class CommentCreateView(LoginRequiredMixin, SingleObjectMixin, FormView):
    """Класс добавления нового комментария к определенному посту."""

    model = Post
    form_class = CommentForm
    template_name = "posts/post_detail.html"
    pk_url_kwarg = "post_id"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post = self.object
        comment.author = self.request.user
        comment.save()
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return self.get_object().get_absolute_url() + "#comments"


class CommentDeleteView(IsAuthorAndLoginRequiredMixin, DeleteView):
    """Класс представления для удаления комментариев."""

    model = Comment

    def get_success_url(self) -> str:
        comment = self.get_object()
        return comment.post.get_absolute_url() + "#comments"

    def get_redirect_url(self):
        return self.get_object().post.get_absolute_url() + "#comments"


class CommentEditView(IsAuthorAndLoginRequiredMixin, UpdateView):
    """Класс представления для редактирования комментариев."""

    template_name = "posts/comment_edit.html"
    model = Comment
    form_class = CommentForm

    def get_success_url(self) -> str:
        comment = self.get_object()
        return comment.post.get_absolute_url() + "#comments"

    def get_redirect_url(self):
        return self.get_object().post.get_absolute_url() + "#comments"

yatube/templates/posts/comment_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
  <h2>Удалить комментарий к посту?</h2>
  <h3>{{ comment.post.title }}</h3>
  <hr />
  <p>{{ comment.created }}</p>
  <p>{{ comment.text }}</p>
  <form class="form-horizontal" method="post">
    {% csrf_token %}
    <div class="form-actions">
      <button type="submit" class="btn btn-primary">Удалить</button>
    </div>
  </form>
{% endblock %}

yatube/templates/posts/comment_edit.html
{% extends "base.html" %}
{% load static %}
{% load post_tag %}
{% block title %}
  Редактирование комментария
{% endblock %}
{% block content %}
    <main>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-12 p-0">
            <div class="card text-bg-dark">
              <div class="card-header text-center ">
                <h3 class="card-title">Редактирование комментария</h3>                
              </div>
              <div class="card-body">        
                <form method="post" {% if action_url %} action="{% url action_url %}" {% endif %}>
                  {% csrf_token %}
                  <div class="mb-3 post_create_text">
                    <label for="" class="form-label">{{form.text.label}}</label>
                    {{form.text|addclass:'form-control text-bg-dark'}}
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}
{{ post.title }}
{% endblock %}

{% block content %}
<style>
    .weather-card {
        background-color: #e3f2fd;
    }
</style>
<section>
    <!-- Контент -->
    <div class="container">
        <div class="row mt-1">
            <div class="col-lg-12">
                <!-- Карточка поста -->
                <div class="container mt-5">
                    <div class="card mb-3">
                        <div class="row g-0">
                            <!-- Изображение -->
                            <div class="col-md-4">
                                {% if post.image %}
                                {% thumbnail post.image '500x600' crop='center' upscale=True as im %}
                                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="img-fluid rounded-start" data-bs-toggle="modal" data-bs-target="#imageModal1" />
                                {% endthumbnail %}
                                {% else %}
                                <img src="{% static 'img/default_img.png' %}" width="500" height="600" class="img-fluid rounded-start" data-bs-toggle="modal" data-bs-target="#imageModal1" />
                                {% endif %}
                            </div> <!-- Изображение -->
                            <!-- Описание поста -->
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h3 class="card-title">{{ post.title }}</h3>
                                    <div class="container px-4 text-center">
                                        <div class="row row-cols-3 gx-3 align-items-stretch justify-content-between">
                                            <div class="col">
                                                <div class="card px-3 weather-card h-100 justify-content-center">
                                                    <h5>Дата создания</h5>
                                                    <h4>{{ post.pub_date|date:'d E Y' }}</h4>
                                                </div>
                                            </div>
                                            <div class="col">
                                                <div class="card px-3 weather-card h-100 justify-content-center">
                                                    <h5>Количество просмотров</h5>
                                                    <h3>{{ post.views_count }}</h3>
                                                </div>
                                            </div>
                                            <div class="col">
                                                <div class="card px-3 weather-card h-100 justify-content-center">
                                                    <h3>
                                                        {% if post.group %}
                                                        <a class="btn post_single_group_name my-3" href="{% url 'posts:post_of_group' post.group.slug %}">{{ post.group.title }}</a>
                                                        {% endif%}
                                                    </h3>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row justify-content-center align-items-lg-stretch mt-2">
                                            <div>
                                                <div class="card mb-3 weather-card">
                                                    <div class="row g-0">
                                                        <div class="col-md-3">
                                                            {% if post.author.avatar %}
                                                            {% thumbnail post.author.avatar '256x256' crop="center" upscale=True as im %}
                                                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="img-fluid rounded-start"
                                                                href="{% url 'users:profile' post.author.username %}">
                                                            {% endthumbnail %}
                                                            {% else %}
                                                            <img src="/media/users/default.png" width="256" height="256" class="img-fluid rounded-start">
                                                            {% endif %}
                                                        </div>
                                                        <div class="col-md-9">
                                                            <div class="card-body">
                                                                <h5 class="card-title"><a href="{% url 'users:profile' post.author.username %}">{{ post.author.get_full_name }}</a></h5>
                                                                <p class="card-text">Всего постов автора: <span> {{ post.count_posts_of_author }}</span></p>
                                                                <p class="card-text">
                                                                    <div class="mt-2">
                                                                        <form action="{% url 'posts:profile_follow' %}" method="post">
                                                                            {% csrf_token %}
                                                                            {% for hidden in form_follow.hidden_fields %}
                                                                            {{ hidden }}
                                                                            {% endfor %}

                                                                            {% if post.is_subscribed %}
                                                                            <button class="btn btn-lg btn-light btn-outline-dark" type="submit">Отписаться</button>
                                                                            {% else %}
                                                                            <button class="btn btn-lg btn-primary" type="submit">Подписаться</button>
                                                                            {% endif %}
                                                                        </form> <!-- Форма подписки и отписки на автора -->
                                                                    </div>
                                                                </p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <!-- Увеличить изображение в модальном окне -->
                                        <div class="modal fade" id="imageModal1" tabindex="-1" aria-labelledby="imageModal1Label" aria-hidden="true">
                                            <div class="modal-dialog modal-lg">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="imageModal1Label">Изображение 1</h5>
                                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                                                    </div>
                                                    <div class="modal-body">
                                                        {% if post.image %}
                                                        {% thumbnail post.image '800x800' crop='center' upscale=True as im %}
                                                        <img src="{{ im.url }}" class="img-fluid" data-bs-toggle="modal" data-bs-target="#imageModal1" />
                                                        {% endthumbnail %}
                                                        {% else %}
                                                        <img src="{% static 'img/default_img.png' %}" width="500" height="600" />
                                                        {% endif %}
                                                    </div>
                                                </div>
                                            </div>
                                        </div> <!-- Увеличить изображение в модальном окне -->
                                    </div>
                                </div>
                            </div> <!-- Описание поста -->
                        </div>
                        <div class="row">
                            <!-- Текст поста -->
                            <div class="card-body">
                                <p class="card-text p-4">{{ post.text|linebreaksbr }}</p>
                                {% if request.user.is_authenticated and request.user == post.author %}
                                <div class="d-flex justify-content-around">
                                    <a class="btn btn-primary btn-lg" href="{% url 'posts:post_edit' post.id %}">редактировать</a>
                                    <a class="btn btn-danger btn-lg" href="{% url 'posts:post_delete' post.id %}">удалить</a>
                                </div>
                                {% endif%}
                            </div> <!-- Текст поста -->
                        </div>
                    </div>
                </div>

                <!-- Блок комментариев -->
                <div id="comments" class="container">
                    {% include 'includes/comments.html' with comments=post.comments.all%}
                </div> <!-- Блок комментариев -->
</section>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% block title %}
  <title>Профайл пользователя {{ author.username }}</title>
{% endblock %}
{% block content %}
  <div class="container-fluid">
    <div class="row">
      <!-- Описание профиля -->
      <div class="col-lg-3 ms-auto mt-5">
        <div class="container">
          <div class="card border-dark">
            <img src="{% if author.avatar %}
                {{ author.avatar.url }}
              {% else %}
                {% static 'img/baseavatar.jpg' %}
              {% endif %}"
              class="card-img-top"
              alt="..." />
            <div class="card-body">
              <ul class="list-group list-group-flush">
                <li class="list-group-item">Всего постов: {{ object_list|length }}</li>
                <li class="list-group-item">{{ object_list.0.author.get_full_name }}</li>
                <li class="list-group-item">{{ author.first_name }}</li>
                <li class="list-group-item">{{ author.last_name }}</li>
                <li class="list-group-item">{{ author.username }}</li>
                <li class="list-group-item">{{ author.email }}</li>
                <li class="list-group-item">{{ author.birth_date|date:'d E Y' }}</li>
              </ul>
              <!-- Форма подписки и отписки на автора -->
              <form action="{% url 'posts:profile_follow' %}" method="post">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                  {{ hidden }}
                {% endfor %}

                {% if is_subscribed %}
                  <button class="btn btn-lg btn-light" type="submit">Отписаться</button>
                {% else %}
                  <button class="btn btn-lg btn-primary" type="submit">Подписаться</button>
                {% endif %}
              </form> <!-- Форма подписки и отписки на автора -->
            </div>
          </div>
        </div>
      </div> <!-- Описание профиля -->

      <div class="col-lg-8 mt-5 m-auto">
        <!-- Список постов -->
        <div class="container-fluid">
          <div class="row justify-content-center overflow-y-scroll" style="height: 85vh;">
            {% for post in page_obj %}
              {% include 'includes/post_list.html' %}
            {% endfor %}
          </div>
        </div> <!-- Список постов -->
        <div class="d-flex justify-content-center">
          {% include 'posts/includes/paginator.html' %}
        </div> <!-- Паджинатор -->
      </div>
    </div>
  </div>
{% endblock %}