yatube/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import CommentViewSet, CustomUserViewSet, GroupViewSet, PostViewSet

router = DefaultRouter()
router.register(r"users", CustomUserViewSet, basename="users")
router.register(
    r"posts/(?P<post_id>\d+)/comments", CommentViewSet, basename="comments"
)
router.register(r"posts", PostViewSet, basename="posts")
router.register(r"groups", GroupViewSet, basename="groups")


urlpatterns = [
    path("", include(router.urls)),
    path("api-auth/", include("rest_framework.urls")),
    path("", include("djoser.urls")),
    path("auth/", include("djoser.urls.authtoken")),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.PostListView.as_view(), name="index"),
    path(
        "group/<slug:slug>/",
        views.GroupPostListView.as_view(),
        name="post_of_group",
    ),
    path(
        "posts/<int:post_id>/",
        views.PostDetailView.as_view(),
        name="post_detail",
    ),
    path("create/", views.PostCreateView.as_view(), name="post_create"),
    path(
        "posts/<int:post_id>/edit/",
        views.PostUpdateView.as_view(),
        name="post_edit",
    ),
    path(
        "posts/<int:post_id>/delete/",
        views.PostDeleteView.as_view(),
        name="post_delete",
    ),
    path("search/", views.SearchPost.as_view(), name="search"),
    path("follow/", views.PostFollowListView.as_view(), name="follow_index"),
    path(
        "profile/follow/",
        views.AddDeleteFollowing.as_view(),
        name="profile_follow",
    ),
    path(
        "comments/<int:pk>/delete/",
        views.CommentDeleteView.as_view(),
        name="comment_delete",
    ),
    path(
        "comments/<int:pk>/edit/",
        views.CommentEditView.as_view(),
        name="comment_edit",
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path

from . import views

app_name = "users"


urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup"),
    path(
        "logout/",
        LogoutView.as_view(template_name="users/logged_out.html"),
        name="logout",
    ),
    path(
        "login/",
        LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "password_reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html"
        ),
        name="password_reset_form",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_change/",
        PasswordChangeView.as_view(
            template_name="users/password_change_form.html"
        ),
        name="password_change_form",
    ),
    path(
        "password_change/done/",
        PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("me/", views.ProfileView.as_view(), name="me"),
    path(
        "users/<str:username>/",
        views.ProfileDetailView.as_view(),
        name="profile",
    ),
    path("profile_edit", views.UserEditView.as_view(), name="profile_edit"),
    path("users/", views.UserListView.as_view(), name="user_list"),
    path(
        "subscriptions/",
        views.SubscriptionListView.as_view(),
        name="subscription_list",
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

handler404 = "core.views.page_not_found"
handler403 = "core.views.csrf_failure"
handler500 = "core.views.server_error"

urlpatterns = [
    path("", include("posts.urls", namespace="posts")),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include("about.urls", namespace="about")),
    path("api/v1/", include("api.urls")),
    path(
        "redoc/",
        TemplateView.as_view(template_name="redoc.html"),
        name="redoc",
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

yatube/users/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.core.exceptions import ValidationError
from django.db import models


class UserQueryset(models.QuerySet):
    def get_is_subscribed(self):
        return self.annotate(
            is_subscribed=models.Exists(
                Follow.objects.filter(author=models.OuterRef("pk")).values(
                    "id"
                )
            )
        )

    def get_posts_count(self):
        return self.annotate(posts_count=models.Count("posts"))

    def get_subscriptions_count(self):
        """Количество подписок."""
        return self.annotate(subscriptions_count=models.Count("follower"))

    def get_subscribers_count(self):
        """Количество подписчиков."""
        return self.annotate(subscribers_count=models.Count("following"))


class CustomUserManager(UserManager):
    def get_queryset(self) -> models.QuerySet:
        return UserQueryset(self.model, using=self._db)

    def get_is_subscribed(self):
        return self.get_queryset().get_is_subscribed()

    def get_subscriptions_count(self):
        return self.get_queryset().get_subscriptions_count()

    def get_subscribers_count(self):
        return self.get_queryset().get_subscribers_count()

    def get_posts_count(self):
        return self.get_queryset().get_posts_count()


class User(AbstractUser):
    """Кастомная модель User."""

    avatar = models.ImageField(
        "Фотография", upload_to="users/%Y/%m/%d", null=True, blank=True
    )
    birth_date = models.DateField("Дата рождения", blank=True, null=True)

    objects = CustomUserManager()


class Follow(models.Model):
    """Модель подписок."""

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower",
        verbose_name="подписчик",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following",
        verbose_name="автор поста",
    )
    created_at = models.DateTimeField("Дата подписки", auto_now_add=True)

    class Meta:
        verbose_name = "Подписка"
        verbose_name_plural = "Подписки"
        constraints = [
            models.UniqueConstraint(
                fields=["user", "author"], name="unique_follow"
            )
        ]

    def clean(self) -> None:
        if self.user == self.author:
            raise ValidationError(
                "Пользователь не можете быть подписан на самого себя."
            )

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.user.username} подписан на {self.author.username}"

yatube/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

User = get_user_model()


class RegisterForm(UserCreationForm):
    """Регистрация нового пользователя."""

    email = forms.EmailField(required=True, label="Адрес электронной почты")

    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            "username",
            "email",
        )

    def clean_email(self):
        email = self.cleaned_data["email"]
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Электронная почта уже используется.")
        return email


class ProfileEditForm(UserChangeForm):
    birth_date = forms.DateField(
        label="Дата рождения",
        widget=forms.DateInput(
            attrs={
                "type": "date",
            }
        ),
    )
    email = forms.EmailField(required=True, label="Адрес электронной почты")

    class Meta(UserChangeForm.Meta):
        model = User
        fields = (
            "avatar",
            "first_name",
            "last_name",
            "username",
            "email",
            "birth_date",
        )

    def clean_email(self):
        email = self.cleaned_data["email"]
        qs = User.objects.exclude(id=self.instance.id).filter(email=email)
        if qs.exists():
            raise forms.ValidationError("Электронная почта уже используется.")
        return email

yatube/users/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models.base import Model as Model
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
)
from posts.forms import FollowForm
from posts.models import Post

from .forms import ProfileEditForm, RegisterForm

User = get_user_model()


class SignUp(CreateView):
    """Класс представление регистрации пользователей."""

    form_class = RegisterForm
    success_url = reverse_lazy("posts:index")
    template_name = "users/signup.html"


class UserEditView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    """Класс представление для редактирования профиля пользователя."""

    model = User
    template_name = "users/profile_form.html"
    form_class = ProfileEditForm
    success_message = "Ваши данные обновлены!"

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

    def get_success_url(self) -> str:
        return reverse("users:me")


class ProfileView(LoginRequiredMixin, DetailView):
    """Класс представление личного кабинета пользователя."""

    model = User
    template_name = "users/me.html"

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context |= {
            "view_posts": Post.objects.filter(
                view_posts__user__id=self.user_id
            ).order_by("-view_posts__date_of_viewing"),
            "posts_of_user": Post.objects.filter(
                author__id=self.user_id
            ).order_by("-pub_date"),
        }
        return context


class ProfileDetailView(LoginRequiredMixin, ListView):
    """
    Класс представления личной страницы пользователя
    с отображением ленты его опубликованных постов.
    """

    template_name = "users/user_detail.html"
    paginate_by = settings.PAGE_SIZE
    queryset = Post.objects.select_related("group")
    context_object_name = "posts"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "author": self.author,
                "form": FollowForm(initial={"author": self.author}),
                "is_subscribed": self.request.user.is_authenticated
                and self.author.is_subscribed,
            }
        )
        return context

    def get(self, request, *args, **kwargs):
        username = self.kwargs.get("username")
        if username == request.user.username:
            return redirect("users:me")
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        username = self.kwargs.get("username")
        self.author = get_object_or_404(
            User.objects.get_is_subscribed(),
            username=username,
        )
        return self.author.posts.select_related("group")


class UserListView(ListView):
    """Класс представление списка всех пользователей."""

    model = User
    paginate_by = 8


class SubscriptionListView(LoginRequiredMixin, ListView):
    """Класс представление подписок пользователей."""

    model = User
    paginate_by = 8

    def get_queryset(self):
        queryset = User.objects.filter(
            following__user__id=self.request.user.id
        )
        return queryset

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Выход
            </div>
            <div class="card-body">
                <p>
                    Вы вышли из своей учётной записи. Ждём вас снова!
                </p>
                <a href="{% url 'users:login' %}" class="btn btn-primary">Войти</a>
                <a href="{% url 'posts:index' %}" class="btn btn-primary">Вернуться на гланую страницу</a>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load post_tag %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/me.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% load post_tag %}
{% block title %}
  Личный кабинет
{% endblock %}
{% block content %}
  <section>
    <!-- Контент -->
    <div class="container">
      <div class="row mt-1">
        <div class="col-lg-12">
          <!-- Контент на странице -->
          <div class="row">
            <div class="container mt-5">
              <div class="row">
                <!-- Профиль с данными пользователя -->
                <div class="col-md-5">
                  <div class="card border-dark">
                    <img src="
                    {% if request.user.avatar %}
                        {{ request.user.avatar.url }}
                      {% else %}
                        {% static 'img/baseavatar.jpg' %}
                      {% endif %}
                      "
                      class="card-img-top"
                      alt="..." />
                    <div class="card-body">
                      <ul class="list-group list-group-flush">
                        <li class="list-group-item">{{ request.user.first_name }}</li>
                        <li class="list-group-item">{{ request.user.last_name }}</li>
                        <li class="list-group-item">{{ request.user.username }}</li>
                        <li class="list-group-item">{{ request.user.email }}</li>
                      </ul>
                      <a href="{% url 'users:profile_edit' %}" class="btn btn-primary">Редактировать</a>
                    </div>
                  </div>
                </div> <!-- Конец Профиля с данными пользователя -->
                <!-- Список постов -->
                <div class="col-md-7">
                  <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Ваши посты</h3>
                    <div class="container" id="cart-items-container">
                      <div class="card mb-3 text-bg-light shadow-lg" style="max-height: 400px;">
                        <ul class="list-group list-group-flush overflow-y-scroll">
                          {% for post in posts_of_user %}
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                              <a href="{% url 'posts:post_detail' post.id %}">{{ post.title }}</a>
                              <span class="badge bg-secondary rounded-pill">{{ post.pub_date|time_since_post }}</span>
                            </li>
                          {% endfor %}
                        </ul>
                      </div>
                      <div class="card mb-3 shadow-lg">
                        <div class="card-footer">
                          <p class="float-left">
                            <h4>Всего <span class="badge bg-secondary">{{ posts_of_user|length }}</span> пост(ов)</h4>
                          </p>
                        </div>
                      </div>
                      <a class="btn btn-dark" href="{% url 'posts:post_create' %}">Создать новый пост</a>
                    </div>
                  </div>
                </div> <!-- Конец Список постов -->

                <!--  -->
                <div class="col-md-12">
                  <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Доска</h3>
                    <!-- Аккордионы -->
                    <div class="container">
                      <div class="accordion" id="accordionExample">
                        <!-- История просмотров текущего пользователя -->
                        <div class="accordion-item">
                          <h2 class="accordion-header" id="heading1"><button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse1" aria-expanded="false" aria-controls="collapse1">История просмотров | Статус:<strong class="mx-2">Активны</strong></button></h2>
                          <div id="collapse1" class="accordion-collapse collapse show" aria-labelledby="heading1" data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                              <div class="container">
                                <div class="row flex-nowrap overflow-scroll">
                                  {% for post in view_posts %}
                                    <div class="card" style="width: 18rem;">
                                      <img src="
                                      {% if post.image %}
                                          {{ post.image.url }}
                                        {% else %}
                                          {% static 'img/default_img.png' %}
                                        {% endif %}
                                        "
                                        class="card-img-top"
                                        alt="..." />
                                      <div class="card-body">
                                        <h5 class="card-title">{{ post.title }}</h5>
                                        <a href="{% url 'posts:post_detail' post.id %}" class="btn btn-primary">Читать</a>
                                      </div>
                                    </div>
                                  {% endfor %}
                                </div>
                              </div>
                            </div>
                          </div>
                        </div> <!-- История просмотров текущего пользователя -->
                        <div class="accordion-item">
                          <h2 class="accordion-header" id="heading2"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse2" aria-expanded="false" aria-controls="collapse2">Свободный аккордион для будущей реализации | Статус: <strong>Неизвестно</strong></button></h2>
                          <div id="collapse2" class="accordion-collapse collapse" aria-labelledby="heading2" data-bs-parent="#accordionExample">
                            <div class="accordion-body"></div>
                          </div>
                        </div>
                      </div>
                    </div> <!-- Аккордионы -->
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}
  Пароль изменён
{% endblock%}
{% block content %}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Пароль изменён
              </div>
              <div class="card-body"> 
                <p>Пароль изменён успешно</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %} Сброс пароля {% endblock %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
              </div>
              <div class="card-body"> 
                <form method="post" 
                {% if action_url %}
                  action="{% url action_url %}"
                {% endif %}>
                {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_email">
                      Адрес электронной почты
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Сбросить пароль
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>  
      </div>
{% endblock %}

yatube/templates/users/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% load user_filters %}
{% block title %}
  <title>Профайл пользователя {{ author.username }}</title>
{% endblock %}
{% block content %}
  <section>
    <!-- Контент -->
    <div class="container">
      <div class="row mt-1">
        <div class="col-lg-12">
          <!-- Контент на странице -->
          <div class="row">
            <div class="container mt-5">
              <div class="row">
                <!-- Профиль с данными пользователя -->
                <div class="col-md-5">
                  <div class="card border-dark">
                    <img src="
                    {% if request.user.avatar %}
                        {{ request.user.avatar.url }}
                      {% else %}
                        {% static 'img/baseavatar.jpg' %}
                      {% endif %}
                      "
                      class="card-img-top"
                      alt="..." />
                    <div class="card-body">
                      <ul class="list-group list-group-flush">
                        <li class="list-group-item">{{ request.user.first_name }}</li>
                        <li class="list-group-item">{{ request.user.last_name }}</li>
                        <li class="list-group-item">{{ request.user.username }}</li>
                        <li class="list-group-item">{{ request.user.email }}</li>
                      </ul>
                      <a href="#" class="btn btn-primary">Редактировать</a>
                    </div>
                  </div>
                </div> <!-- Конец Профиля с данными пользователя -->
                <!-- Список постов -->
                <div class="col-md-7">
                  <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Ваши посты</h3>
                    <div class="container" id="cart-items-container">
                      <div class="card mb-3 text-bg-light shadow-lg" style="max-height: 400px;">
                        <ul class="list-group list-group-flush overflow-y-scroll">
                          {% for post in user.posts.all %}
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                              <a href="{% url 'posts:post_detail' post.id %}">{{ post.title }}</a>
                              <span class="badge bg-secondary rounded-pill">{{ post.pub_date|time_since_post }}</span>
                            </li>
                          {% endfor %}
                        </ul>
                      </div>
                      <div class="card mb-3 shadow-lg">
                        <div class="card-footer">
                          <p class="float-left">
                            <h4>Всего <span class="badge bg-secondary">{{ user.posts.count }}</span> пост(ов)</h4>
                          </p>
                        </div>
                      </div>
                      <a class="btn btn-dark" href="{% url 'posts:post_create' %}">Создать новый пост</a>
                    </div>
                  </div>
                </div> <!-- Конец Список постов -->

                <!--  -->
                <div class="col-md-12">
                  <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Доска</h3>
                    <!-- Разметка заказов -->
                    <div class="container">
                      <div class="accordion" id="accordionExample">
                        <div class="accordion-item">
                          <h2 class="accordion-header" id="heading1"><button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse1" aria-expanded="false" aria-controls="collapse1">История просмотров | Статус:<strong class="mx-2">Активны</strong></button></h2>
                          <div id="collapse1" class="accordion-collapse collapse show" aria-labelledby="heading1" data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                              <div class="container">
                                <div class="row flex-nowrap overflow-scroll">
                                  {% for post in request.user.posts.all %}
                                    <div class="card" style="width: 18rem;">
                                      <img src="
                                      {% if post.image %}
                                          {{ post.image.url }}
                                        {% else %}
                                          {% static 'img/default_img.png' %}
                                        {% endif %}
                                        "
                                        class="card-img-top"
                                        alt="..." />
                                      <div class="card-body">
                                        <h5 class="card-title">{{ post.title }}</h5>
                                        <a href="{% url 'posts:post_detail' post.id %}" class="btn btn-primary">Читать</a>
                                      </div>
                                    </div>
                                  {% endfor %}
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="accordion-item">
                          <h2 class="accordion-header" id="heading2"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse2" aria-expanded="false" aria-controls="collapse2">Свободный аккордион для будущей реализации | Статус: <strong>Неизвестно</strong></button></h2>
                          <div id="collapse2" class="accordion-collapse collapse" aria-labelledby="heading2" data-bs-parent="#accordionExample">
                            <div class="accordion-body"></div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <!--  -->
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}